apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mongo
spec:
  selector:
    matchLabels:
      app: demo-mongo
  template:
    metadata:
      labels:
        app: demo-mongo
    spec:
      containers:
        - name: demo-mongo
          image: mongo:latest
          env:
            #- name: MONGO_INITDB_ROOT_USERNAME
            # value: demo
            #- name: MONGO_INITDB_ROOT_PASSWORD
            #  value: demo
            - name: MONGO_INITDB_DATABASE
              value: demo-db
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc